# Generated by Django 4.0.3 on 2022-04-20 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlighted', models.TextField()),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('neuroticism', models.IntegerField(default=0)),
                ('extraversion', models.IntegerField(default=0)),
                ('openness', models.IntegerField(default=0)),
                ('agreeableness', models.IntegerField(default=0)),
                ('conscientiousness', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
    ]
